((Symbol as any).metadata ??= Symbol.for("Symbol.metadata"));

/**
 * Supported primitives for automated string-to-value casting during CSV parsing.
 */
export type ColumnType = "string" | "number" | "boolean" | "date";

/**
 * Custom transformation function converting a raw string cell into a typed domain value.
 *
 * @template T Target type of the parsed value.
 */
export type TransformFn<T = any> = (value: string) => T;

export interface NumberCastOptions 
{
    /** 
     * The accepted decimal separator character. 
     * @default "." 
     */
    decimalSeparator?: "." | ",";

    /**
     * Determines how invalid number strings (e.g., "N/A", "abc") are handled.
     * 
     * - If `true`: The parser will immediately throw an error (`Invalid number format`) and halt execution.
     * - If `false` (or omitted): The parser will silently catch the failure and return `null`.
     * 
     * Useful for critical or financial data where a malformed number must not be ignored.
     * 
     * @default false
     */
    strict?: boolean;
}

/**
 * Internal configuration metadata associated with a decorated CSV column property.
 * This is generated by `@CsvColumn` or `@CsvIndex` and consumed by the parser.
 */
export interface ColumnMeta 
{
    /** 
     * The exact raw CSV header string matching this field (e.g., `"First Name *"`). 
     * Used for header-based lookups during parsing.
     */
    header?: string;

    /** 
     * Explicit 0-based column index. 
     * Used for positional lookups when reading headerless CSV files.
     */
    index?: number;

    /** 
     * Output ordering priority when writing rows (e.g., 0, 1, 2...).
     * Determines the horizontal sequence of columns in the generated CSV file.
     */
    order?: number;

    /** 
     * The actual property name on the TypeScript DTO class (e.g., `"firstName"`). 
     * Used by the parser to dynamically assign values to the instantiated object.
     */
    propertyKey: string;

    /** 
     * Strict validation flag. 
     * If `true`, the parser will reject the row (`MISSING_REQUIRED_COLUMN`) if the cell is completely empty.
     */
    required?: boolean;

    /**
     * Target primitive type for automated value conversion.
     * Tells the parser to automatically cast the raw string to a `"number"`, `"boolean"`, or `"date"`.
     */
    type?: ColumnType;

    /**
     * Custom transformation function.
     * Executed per-cell to convert the raw CSV string into a complex typed domain value (e.g., Arrays, specific Date formats).
     */
    transform?: TransformFn;
}

/**
 * Configuration options for the `@CsvColumn` decorator.
 */
export interface CsvColumnOptions 
{
    /** 
     * Statically declares this field as mandatory.
     * Rows with empty or missing values for this column will automatically trigger a validation error (`MISSING_REQUIRED_COLUMN`).
     */
    required?: boolean;

    /** 
     * Explicit column output priority used exclusively when writing data (`Csv.streamWriterWithClass`).
     * 
     * - Dictates the exact horizontal position (e.g., `0` is the first column).
     * - Has **no impact** during parsing (`Csv.streamReaderWithClass`), as reading maps dynamically to the source header.
     */
    order?: number;

    /**
     * Target primitive type for automated value conversion.
     * Automatically casts raw CSV strings to Numbers, Booleans, or Dates safely.
     */
    type?: ColumnType;

    /**
     * Static, model-level custom value converter applied whenever a cell for this property is parsed.
     */
    transform?: TransformFn;

    /** 
     * Custom truthy / falsy definitions when `type: "boolean"` is used. 
     */
    booleanValues?: BooleanCastOptions;

    numberOptions?: NumberCastOptions;
}

/**
 * Compiled CSV metadata schema for a specific decorated DTO class.
 * 
 * This schema is built once and cached. It flattens all decorator metadata 
 * (`@CsvColumn`, `@CsvIndex`) into highly optimized maps and arrays, 
 * enabling zero-overhead, O(1) lookups during stream parsing and writing.
 *
 * @template T Type of the decorated class instance.
 */
export interface CsvClassSchema<T> 
{
    /** 
     * Array of all raw CSV column headers discovered on the class.
     * Sorted according to the `order` property defined in the decorators.
     */
    headers: string[];

    /** 
     * Class property keys aligned strictly with the `headers` array. 
     * Used for ultra-fast positional serialization when writing CSVs.
     */
    propertyKeys: (keyof T)[];

    /** 
     * Map linking a raw CSV header string directly to its corresponding TypeScript property key.
     * Used during parsing when `hasHeader` is true.
     */
    headerToProperty: Map<string, string>;

    /** 
     * Map linking a 0-based column index directly to its corresponding TypeScript property key.
     * Used during parsing for headerless CSV files (`@CsvIndex`).
     */
    indexToProperty: Map<number, string>;

    /** 
     * Pre-computed list of headers (strings) or column indices (numbers) marked with `{ required: true }`. 
     * Merged at runtime with user-provided `requiredColumns` to enforce strict validation.
     */
    requiredColumns: (string | number)[];

    /**
     * Pre-compiled map associating class property keys with their static transformation functions.
     * Generated from decorators configured with `{ type: ... }` or `{ transform: ... }`.
     * 
     * During stream initialization, this map is converted into an indexed array 
     * guaranteeing direct O(1) casting per row without runtime key lookups.
     */
    propertyTransformers: Map<string, TransformFn>;
}

/**
 * Configuration options for boolean value casting.
 */
export interface BooleanCastOptions 
{
    /** 
     * String tokens considered as `true` (case-insensitive).
     * @default ["1", "true", "yes", "y", "oui", "o"]
     */
    truthy?: readonly string[];

    /** 
     * Optional string tokens considered as `false` (case-insensitive).
     * If provided, values not matching either list can return null or false.
     */
    falsy?: readonly string[];
}

/**
 * Generic constructor interface for instantiable class DTOs.
 */
export type ClassConstructor<T> = new (...args: any[]) => T;

export const CSV_SCHEMA_KEY = Symbol.for("__csv_schema__");
const CSV_CACHE = new WeakMap<Function, CsvClassSchema<any>>();
const DEFAULT_TRUTHY = ["1", "true", "yes", "y", "oui", "o"] as const;

function resolveTransformer(
    type?: ColumnType,
    custom?: TransformFn,
    boolOptions?: BooleanCastOptions,
    numOptions?: NumberCastOptions
): TransformFn | undefined 
{
    if (custom) return custom;

    switch (type) 
    {
        case "boolean":
            {
                const truthyList = (boolOptions?.truthy ?? DEFAULT_TRUTHY).map(v => v.trim().toLowerCase());
                const truthySet = new Set(truthyList);

                if (boolOptions?.falsy && boolOptions.falsy.length > 0) 
                {
                    const falsySet = new Set(boolOptions.falsy.map(v => v.trim().toLowerCase()));
                    return (v: string) => 
                    {
                        const s = v.trim().toLowerCase();
                        if (truthySet.has(s)) return true;
                        if (falsySet.has(s)) return false;
                        return null;
                    };
                }

                return (v: string) => truthySet.has(v.trim().toLowerCase());
            }

        case "number":
            return (v: string) => 
            {
                let trimmed = v.trim();
                if (trimmed === "") return null;

                if (numOptions?.decimalSeparator === ",") 
                {
                    trimmed = trimmed.replace(",", ".");
                }

                const num = Number(trimmed);
                if (isNaN(num))
                {
                    if (numOptions?.strict) throw new Error(`Invalid number format: "${v}"`);
                    return null;
                }
                return num;
            };

        case "date":
            return (v: string) => (v.trim() === "" ? null : new Date(v));

        default:
            return undefined;
    }
}

/**
 * Links a class property to a specific column name in your CSV file.
 * This is the easiest way to read and write CSVs with TypeScript.
 *
 * @example
 * ```ts
 * class Employee {
 *   // Looks for the exact column "Full Name" in the file
 *   @CsvColumn("Full Name", { required: true })
 *   name!: string;
 * 
 *   // Automatically turns the text "true", "1", or "yes" into a boolean
 *   @CsvColumn("Is Active", { type: "boolean" })
 *   isActive!: boolean;
 * }
 * ```
 *
 * @param header The exact column name in the CSV file (e.g., "Email Address").
 * @param options Extra settings (like making the field required, or converting types).
 */
export function CsvColumn(header: string, options?: CsvColumnOptions): any 
{
    return registerDecorator({
        header,
        required: options?.required,
        order: options?.order,
        type: options?.type,
        transform: resolveTransformer(options?.type, options?.transform, options?.booleanValues, options?.numberOptions),
    });
}

/**
 * Links a class property to a column position (0, 1, 2...) instead of a name.
 * Use this when your CSV file does NOT have a header row.
 *
 * @example
 * ```ts
 * class LogLine {
 *   @CsvIndex(0, { type: "date" }) timestamp!: Date; // First column
 *   @CsvIndex(1) message!: string;                   // Second column
 * }
 * ```
 *
 * @param index The column number (starting at 0 for the first column).
 */
export function CsvIndex(
    index: number,
    options?: { required?: boolean; type?: ColumnType; booleanValues?: BooleanCastOptions; numberOptions?: NumberCastOptions; transform?: TransformFn }
): any 
{
    return registerDecorator({
        index,
        order: index,
        required: options?.required,
        type: options?.type,
        transform: resolveTransformer(options?.type, options?.transform, options?.booleanValues, options?.numberOptions),
    });
}

function registerDecorator(meta: {
    header?: string;
    index?: number;
    order?: number;
    type?: ColumnType;
    required?: boolean;
    transform?: TransformFn;
}): any
{
    return (targetOrContext: any, contextOrKey?: string | symbol | ClassFieldDecoratorContext) =>
    {
        // Détection propre des décorateurs TC39
        if (contextOrKey && typeof contextOrKey === "object" && "kind" in contextOrKey)
        {
            const context = contextOrKey as ClassFieldDecoratorContext;
            const propName = String(context.name);

            if (context.metadata)
            {
                if (!context.metadata[CSV_SCHEMA_KEY])
                {
                    context.metadata[CSV_SCHEMA_KEY] = [];
                }
                (context.metadata[CSV_SCHEMA_KEY] as any[]).push({ ...meta, propertyKey: propName });
            }
            else
            {
                // Fallback de sécurité si le polyfill Symbol.metadata est absent ou incomplet
                context.addInitializer(function (this: any) 
                {
                    if (!this.constructor[CSV_SCHEMA_KEY])
                    {
                        this.constructor[CSV_SCHEMA_KEY] = [];
                    }

                    // Empêcher les doublons si la classe est instanciée plusieurs fois
                    const existant = this.constructor[CSV_SCHEMA_KEY].find((m: any) => m.propertyKey === propName);
                    if (!existant)
                    {
                        this.constructor[CSV_SCHEMA_KEY].push({ ...meta, propertyKey: propName });
                    }
                });
            }
            return;
        }

        // Décorateurs expérimentaux (Legacy TypeScript)
        enregistrerMeta(targetOrContext.constructor, String(contextOrKey), meta);
    };
}

function enregistrerMeta(
    ctor: any,
    propertyKey: string,
    meta: { header?: string; index?: number; order?: number; required?: boolean; transform?: TransformFn }
): void
{
    if (!ctor[CSV_SCHEMA_KEY])
    {
        ctor[CSV_SCHEMA_KEY] = [];
    }
    ctor[CSV_SCHEMA_KEY].push({ ...meta, propertyKey });
}

/**
 * Retrieves or compiles the CSV mapping schema for a decorated class constructor.
 * Uses a WeakMap cache to eliminate parsing overhead across multiple stream calls.
 *
 * @template T Type of the target class.
 * @param cls The class constructor containing decorator metadata.
 * @returns Compiled schema object, or `null` if no decorators are defined.
 */
export function getCsvSchema<T>(cls: ClassConstructor<T>): CsvClassSchema<T> | null
{
    const cached = CSV_CACHE.get(cls);
    if (cached)
        return cached;

    const tc39Meta = (cls as any)[Symbol.metadata]?.[CSV_SCHEMA_KEY];
    const legacyMeta = (cls as any)[CSV_SCHEMA_KEY];
    const metas = tc39Meta ?? legacyMeta;

    if (!metas || metas.length === 0)
        return null;

    const sortedMetas = [...metas].sort((a, b) =>
    {
        const orderA = a.order ?? (a.index !== undefined ? a.index : 9999);
        const orderB = b.order ?? (b.index !== undefined ? b.index : 9999);
        return orderA - orderB;
    });

    const headers: string[] = [];
    const propertyKeys: (keyof T)[] = [];
    const headerToProperty = new Map<string, string>();
    const indexToProperty = new Map<number, string>();
    const propertyTransformers = new Map<string, TransformFn>();
    const requiredColumns: (string | number)[] = [];

    for (let i = 0; i < sortedMetas.length; i++)
    {
        const m = sortedMetas[i];
        const propKey = m.propertyKey as keyof T;

        if (m.transform)
        {
            propertyTransformers.set(m.propertyKey, m.transform);
        }

        if (m.header !== undefined)
        {
            headers.push(m.header);
            propertyKeys.push(propKey);
            headerToProperty.set(m.header, m.propertyKey);
            if (m.required) requiredColumns.push(m.header);
        }

        if (m.index !== undefined)
        {
            indexToProperty.set(m.index, m.propertyKey);
            if (m.required) requiredColumns.push(m.index);
        }
    }

    const compiled: CsvClassSchema<T> = {
        headers,
        propertyKeys,
        headerToProperty,
        indexToProperty,
        propertyTransformers,
        requiredColumns,
    };

    CSV_CACHE.set(cls, compiled);
    return compiled;
}